apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  labels:
    name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: orazio.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: catalog-svc
            port: 
              number: 80
